name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env:
        DOCKER_USER: tahataqa
        DOCKER_PASSWORD: Taha@1978@Taha
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file .dockerfile --tag ${{secrets.DOCKER_USER}}/uom-archive
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USER}}/uom-archive
